"""
Trip SQLAlchemy model — stores AI-generated travel itineraries.
"""

import uuid

from sqlalchemy import Float, Integer, JSON, String, Text, Uuid
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base, TimestampMixin


class Trip(Base, TimestampMixin):
    """Stores trip itineraries generated by the AI."""

    __tablename__ = "trips"

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )

    # ── User inputs ───────────────────────────────────────────────────────────
    destination: Mapped[str] = mapped_column(String(255), nullable=False)
    duration: Mapped[int] = mapped_column(Integer, nullable=False)
    budget: Mapped[float] = mapped_column(Float, nullable=False)
    currency: Mapped[str] = mapped_column(String(10), default="INR", nullable=False)
    interests: Mapped[list] = mapped_column(JSON, default=list, nullable=False)

    # ── AI-generated content ──────────────────────────────────────────────────
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    budget_breakdown: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    days: Mapped[list] = mapped_column(JSON, default=list)
    travel_tips: Mapped[list] = mapped_column(JSON, default=list)

    def __repr__(self) -> str:
        return f"<Trip id={self.id} destination={self.destination!r} budget={self.budget}>"
