import { Itinerary, BudgetBreakdownData, ChatMessage, ChatSuggestion } from "@/types";

// ─── Mock Tokyo Itinerary ─────────────────────────────────────

export const MOCK_ITINERARY: Itinerary = {
  id: "itinerary_tokyo_demo",
  title: "7 Days in Tokyo",
  destination: {
    city: "Tokyo",
    country: "Japan",
    countryCode: "JP",
    coordinates: { lat: 35.6762, lng: 139.6503 },
    timezone: "Asia/Tokyo",
  },
  startDate: "2025-06-15",
  endDate: "2025-06-22",
  numTravelers: 2,
  preferences: {
    styles: ["cultural", "food-and-drink", "adventure"],
    budget: "moderate",
    currency: "USD",
    accommodation: ["hotel"],
    transport: ["train"],
  },
  status: "complete",
  generatedAt: new Date().toISOString(),
  summary: {
    totalDays: 7,
    totalActivities: 21,
    estimatedBudget: { amount: 2400, currency: "USD", perPerson: false },
    topHighlights: [
      "Senso-ji Temple at sunrise",
      "Tsukiji Outer Market breakfast",
      "TeamLab Borderless",
      "Mt. Fuji day trip",
      "Shibuya Crossing at night",
    ],
    destinationTags: ["Cultural", "Food", "Technology", "Nature"],
  },
  days: [
    {
      id: "day-1",
      date: "2025-06-15",
      dayNumber: 1,
      title: "Arrival & Shinjuku",
      summary: "Touch down in Tokyo, check in, and get your bearings in the electric Shinjuku district.",
      theme: "Arrival & Exploration",
      weatherNote: "Partly cloudy, 24°C — perfect walking weather",
      estimatedCost: { amount: 180, currency: "USD", perPerson: false },
      activities: [
        {
          id: "act-1-1",
          title: "Arrive at Narita / Haneda Airport",
          description: "Clear customs, pick up your IC card (Suica/Pasmo), and board the express train to central Tokyo.",
          category: "transport",
          status: "confirmed",
          startTime: "12:00",
          endTime: "14:00",
          duration: 120,
          location: { city: "Tokyo", country: "Japan", countryCode: "JP" },
          cost: { amount: 32, currency: "USD", perPerson: true },
          tips: ["Get a Suica card at the airport — works for trains, buses, and convenience stores", "Narita Express is the fastest option"],
          tags: ["transport", "arrival"],
        },
        {
          id: "act-1-2",
          title: "Check-In: Shinjuku Granbell Hotel",
          description: "A stylish boutique hotel steps from Shinjuku Station — perfectly located for exploring.",
          category: "accommodation",
          status: "confirmed",
          startTime: "15:00",
          endTime: "16:00",
          duration: 60,
          location: { city: "Shinjuku", country: "Japan", countryCode: "JP" },
          cost: { amount: 140, currency: "USD", perPerson: false },
          rating: 4.7,
          tips: ["Early check-in available if you request it in advance"],
          tags: ["hotel", "boutique"],
        },
        {
          id: "act-1-3",
          title: "Shinjuku Golden Gai Bar Crawl",
          description: "Wander the labyrinthine alleyways of Golden Gai — hundreds of tiny bars, each with its own personality. The perfect intro to Tokyo nightlife.",
          category: "entertainment",
          status: "confirmed",
          startTime: "20:00",
          endTime: "23:00",
          duration: 180,
          location: { city: "Shinjuku", country: "Japan", countryCode: "JP" },
          cost: { amount: 35, currency: "USD", perPerson: true },
          rating: 4.9,
          tips: ["Don't be shy — most bars welcome tourists", "Cover charge is usually ¥500–1000"],
          tags: ["nightlife", "local"],
        },
      ],
    },
    {
      id: "day-2",
      date: "2025-06-16",
      dayNumber: 2,
      title: "Asakusa & Ueno",
      summary: "Immerse yourself in old Tokyo at Senso-ji Temple, then explore world-class museums in Ueno.",
      theme: "Old Tokyo & Culture",
      weatherNote: "Sunny, 26°C — great for outdoor temple walks",
      estimatedCost: { amount: 120, currency: "USD", perPerson: false },
      activities: [
        {
          id: "act-2-1",
          title: "Senso-ji Temple at Sunrise",
          description: "Beat the crowds by arriving early at Tokyo's oldest temple. The Nakamise shopping street and Thunder Gate are stunning in the morning light.",
          category: "sightseeing",
          status: "confirmed",
          startTime: "07:00",
          endTime: "09:00",
          duration: 120,
          location: { city: "Asakusa", country: "Japan", countryCode: "JP" },
          cost: { amount: 0, currency: "USD", perPerson: true },
          rating: 4.9,
          tips: ["Free entry — the main hall opens at 6am", "Buy a fortune (omikuji) for ¥100"],
          tags: ["temple", "iconic", "free"],
        },
        {
          id: "act-2-2",
          title: "Tsukiji Outer Market Breakfast",
          description: "Head to the famous outer market for the freshest sushi and tamagoyaki breakfast you'll ever have.",
          category: "food",
          status: "confirmed",
          startTime: "09:30",
          endTime: "11:00",
          duration: 90,
          location: { city: "Tsukiji", country: "Japan", countryCode: "JP" },
          cost: { amount: 22, currency: "USD", perPerson: true },
          rating: 4.8,
          tips: ["Try Sushi Dai or Daiwa Sushi — expect a queue", "Market opens early, arrive by 9am"],
          tags: ["sushi", "market", "breakfast"],
        },
        {
          id: "act-2-3",
          title: "Tokyo National Museum",
          description: "The largest art museum in Japan, with over 110,000 artifacts spanning 2,000 years of Japanese history.",
          category: "culture",
          status: "confirmed",
          startTime: "13:00",
          endTime: "16:00",
          duration: 180,
          location: { city: "Ueno", country: "Japan", countryCode: "JP" },
          cost: { amount: 9, currency: "USD", perPerson: true },
          rating: 4.7,
          tips: ["Tuesday–Sunday, closed Mondays", "Audio guide available in English"],
          tags: ["museum", "history", "art"],
        },
      ],
    },
    {
      id: "day-3",
      date: "2025-06-17",
      dayNumber: 3,
      title: "Shibuya & Harajuku",
      summary: "Witness the world's busiest crossing, explore teen fashion in Harajuku, and dine at a rooftop in Omotesando.",
      theme: "Pop Culture & Fashion",
      weatherNote: "Warm, 27°C — light cloud cover",
      estimatedCost: { amount: 150, currency: "USD", perPerson: false },
      activities: [
        {
          id: "act-3-1",
          title: "Meiji Shrine & Yoyogi Park",
          description: "Start the morning with a peaceful stroll through forested Meiji Shrine, then people-watch in adjacent Yoyogi Park.",
          category: "nature",
          status: "confirmed",
          startTime: "08:30",
          endTime: "10:30",
          duration: 120,
          location: { city: "Harajuku", country: "Japan", countryCode: "JP" },
          cost: { amount: 0, currency: "USD", perPerson: true },
          rating: 4.8,
          tips: ["Free entry", "Wear comfortable shoes — the gravel path is long"],
          tags: ["shrine", "nature", "free"],
        },
        {
          id: "act-3-2",
          title: "Takeshita Street & Harajuku Crepes",
          description: "Dive into Harajuku's famously wild fashion street and grab one of the legendary rainbow crepes.",
          category: "shopping",
          status: "confirmed",
          startTime: "11:00",
          endTime: "13:00",
          duration: 120,
          location: { city: "Harajuku", country: "Japan", countryCode: "JP" },
          cost: { amount: 40, currency: "USD", perPerson: true },
          rating: 4.5,
          tips: ["Weekdays are less crowded than weekends", "Marion Crepes is the classic choice"],
          tags: ["shopping", "food", "fashion"],
        },
        {
          id: "act-3-3",
          title: "Shibuya Crossing at Night",
          description: "Experience the iconic scramble crossing at its most electric — hundreds of people crossing simultaneously under neon lights.",
          category: "sightseeing",
          status: "confirmed",
          startTime: "19:00",
          endTime: "21:00",
          duration: 120,
          location: { city: "Shibuya", country: "Japan", countryCode: "JP" },
          cost: { amount: 0, currency: "USD", perPerson: true },
          rating: 5.0,
          tips: ["Watch from the Starbucks above for the aerial view", "Best after dark for the full neon effect"],
          tags: ["iconic", "free", "night"],
        },
      ],
    },
    {
      id: "day-4",
      date: "2025-06-18",
      dayNumber: 4,
      title: "Mt. Fuji Day Trip",
      summary: "Take a scenic train to Kawaguchiko, enjoy stunning Fuji views, and explore the lakeside village.",
      theme: "Nature Escape",
      weatherNote: "Clear skies expected — ideal for Fuji views",
      estimatedCost: { amount: 110, currency: "USD", perPerson: false },
      activities: [
        {
          id: "act-4-1",
          title: "Shinjuku → Kawaguchiko Express",
          description: "Board the Fujikyu-Shinjuku Limited Express for a scenic 2-hour journey to the Fuji Five Lakes region.",
          category: "transport",
          status: "confirmed",
          startTime: "07:30",
          endTime: "09:30",
          duration: 120,
          location: { city: "Shinjuku", country: "Japan", countryCode: "JP" },
          cost: { amount: 28, currency: "USD", perPerson: true },
          rating: 4.6,
          tips: ["Book tickets in advance, especially on weekends"],
          tags: ["train", "scenic"],
        },
        {
          id: "act-4-2",
          title: "Lake Kawaguchiko & Fuji Views",
          description: "Walk the lakeside path for iconic reflections of Mt. Fuji. Visit Chureito Pagoda for the classic postcard shot.",
          category: "nature",
          status: "confirmed",
          startTime: "10:00",
          endTime: "15:00",
          duration: 300,
          location: { city: "Kawaguchiko", country: "Japan", countryCode: "JP" },
          cost: { amount: 5, currency: "USD", perPerson: true },
          rating: 4.9,
          tips: ["Best views in the morning before afternoon clouds roll in", "Rent a bike to explore the lakeside"],
          tags: ["nature", "fuji", "iconic"],
        },
      ],
    },
    {
      id: "day-5",
      date: "2025-06-19",
      dayNumber: 5,
      title: "Akihabara & TeamLab",
      summary: "Explore the electric town of anime and tech, then lose yourself in the immersive digital art of TeamLab.",
      theme: "Technology & Digital Art",
      weatherNote: "Warm, 28°C",
      estimatedCost: { amount: 140, currency: "USD", perPerson: false },
      activities: [
        {
          id: "act-5-1",
          title: "Akihabara Electric Town",
          description: "Tokyo's legendary district for electronics, anime, manga, and gaming culture. Multi-floor arcades and collector shops await.",
          category: "entertainment",
          status: "confirmed",
          startTime: "10:00",
          endTime: "13:00",
          duration: 180,
          location: { city: "Akihabara", country: "Japan", countryCode: "JP" },
          cost: { amount: 30, currency: "USD", perPerson: true },
          rating: 4.6,
          tips: ["Visit Yodobashi Camera for electronics deals", "Try a maid café for a uniquely Japanese experience"],
          tags: ["anime", "tech", "entertainment"],
        },
        {
          id: "act-5-2",
          title: "TeamLab Borderless",
          description: "The world-famous borderless museum of digital art. Rooms of flowing light, interactive installations, and immersive wonder.",
          category: "entertainment",
          status: "confirmed",
          startTime: "15:00",
          endTime: "18:30",
          duration: 210,
          location: { city: "Azabudai Hills", country: "Japan", countryCode: "JP" },
          cost: { amount: 32, currency: "USD", perPerson: true },
          rating: 5.0,
          bookingUrl: "https://www.teamlab.art/e/borderless-azabudai/",
          tips: ["Book tickets online — often sells out weeks ahead", "Wear comfortable, dark clothing"],
          tags: ["art", "digital", "must-do"],
        },
      ],
    },
    {
      id: "day-6",
      date: "2025-06-20",
      dayNumber: 6,
      title: "Ginza & Odaiba",
      summary: "Window-shop in Tokyo's luxury district, then cross the rainbow bridge to the futuristic waterfront of Odaiba.",
      theme: "Luxury & Waterfront",
      weatherNote: "Sunny and humid, 29°C",
      estimatedCost: { amount: 130, currency: "USD", perPerson: false },
      activities: [
        {
          id: "act-6-1",
          title: "Ginza District Stroll",
          description: "Explore Tokyo's most upscale shopping avenue — flagship stores, galleries, and the iconic Itoya stationery shop.",
          category: "shopping",
          status: "confirmed",
          startTime: "10:00",
          endTime: "12:30",
          duration: 150,
          location: { city: "Ginza", country: "Japan", countryCode: "JP" },
          cost: { amount: 0, currency: "USD", perPerson: true },
          rating: 4.5,
          tips: ["Ginza Six is the flagship mall", "On weekends, Chuo-dori becomes pedestrian-only"],
          tags: ["shopping", "luxury", "free"],
        },
        {
          id: "act-6-2",
          title: "Odaiba & Rainbow Bridge Views",
          description: "Take the Yurikamome monorail across the Rainbow Bridge for stunning bay views. Explore the futuristic Odaiba island.",
          category: "sightseeing",
          status: "confirmed",
          startTime: "14:00",
          endTime: "18:00",
          duration: 240,
          location: { city: "Odaiba", country: "Japan", countryCode: "JP" },
          cost: { amount: 10, currency: "USD", perPerson: true },
          rating: 4.4,
          tips: ["Visit the life-size Gundam statue", "Palette Town has free attractions"],
          tags: ["waterfront", "scenic", "iconic"],
        },
      ],
    },
    {
      id: "day-7",
      date: "2025-06-21",
      dayNumber: 7,
      title: "Roppongi & Farewell",
      summary: "Visit the Mori Art Museum for panoramic city views, shop for last-minute omiyage, and prepare for departure.",
      theme: "Art & Departure",
      weatherNote: "Partly cloudy, 25°C",
      estimatedCost: { amount: 90, currency: "USD", perPerson: false },
      activities: [
        {
          id: "act-7-1",
          title: "Mori Art Museum & Tokyo City View",
          description: "Catch a world-class contemporary art exhibition, then take the elevator to the observation deck for 360° city panoramas.",
          category: "culture",
          status: "confirmed",
          startTime: "10:00",
          endTime: "13:00",
          duration: 180,
          location: { city: "Roppongi", country: "Japan", countryCode: "JP" },
          cost: { amount: 18, currency: "USD", perPerson: true },
          rating: 4.8,
          tips: ["The museum is open until 10pm — sunset views are stunning", "Combo ticket includes the sky deck"],
          tags: ["art", "views", "museum"],
        },
        {
          id: "act-7-2",
          title: "Omiyage Shopping & Airport Transfer",
          description: "Pick up final souvenirs at Don Quijote or a department store basement, then head to the airport for departure.",
          category: "transport",
          status: "confirmed",
          startTime: "14:00",
          endTime: "17:00",
          duration: 180,
          location: { city: "Shinjuku", country: "Japan", countryCode: "JP" },
          cost: { amount: 50, currency: "USD", perPerson: true },
          rating: 4.2,
          tips: ["Tokyo Banana is the classic gift — available at the airport too", "Leave at least 3 hours before your flight"],
          tags: ["shopping", "departure"],
        },
      ],
    },
  ],
};

// ─── Mock Budget Breakdown ────────────────────────────────────

export const MOCK_BUDGET: BudgetBreakdownData = {
  total: 2400,
  currency: "USD",
  perPerson: 1200,
  perDay: 343,
  numTravelers: 2,
  numDays: 7,
  categories: [
    { label: "Accommodation", icon: "🏨", amount: 980, currency: "USD", percentage: 41, color: "emerald" },
    { label: "Food & Dining", icon: "🍜", amount: 560, currency: "USD", percentage: 23, color: "orange" },
    { label: "Transport", icon: "🚄", amount: 380, currency: "USD", percentage: 16, color: "brand" },
    { label: "Activities", icon: "🎭", amount: 320, currency: "USD", percentage: 13, color: "purple" },
    { label: "Shopping", icon: "🛍️", amount: 160, currency: "USD", percentage: 7, color: "pink" },
  ],
};

// ─── Mock Chat Messages ───────────────────────────────────────

export const MOCK_INITIAL_MESSAGES: ChatMessage[] = [
  {
    id: "msg-0",
    role: "assistant",
    content: "I've built your 7-day Tokyo itinerary! Want me to adjust anything? I can swap activities, change the pace, or add more focus on specific interests like food, art, or nightlife.",
    timestamp: new Date(Date.now() - 120000).toISOString(),
  },
];

// ─── Chat Suggestions ─────────────────────────────────────────

export const CHAT_SUGGESTIONS: ChatSuggestion[] = [
  { id: "s1", label: "More food spots", prompt: "Can you add more local food and dining experiences throughout the trip?" },
  { id: "s2", label: "Add a spa day", prompt: "Replace one of the activity-heavy days with a relaxing spa or onsen day." },
  { id: "s3", label: "Shorten to 5 days", prompt: "Condense the itinerary to 5 days, keeping the best highlights." },
  { id: "s4", label: "Budget breakdown", prompt: "Can you estimate the total budget and break it down by category?" },
  { id: "s5", label: "Family-friendly version", prompt: "Make this trip more suitable for a family with young children." },
];
